# Single node, SSL mode
# Example: https://github.com/apache/kafka/blob/trunk/docker/examples/docker-compose-files/single-node/ssl/docker-compose.yml

---
services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    restart: always
    ports:
      - '9092:9092'
    volumes:
      - ./secrets:/etc/kafka/secrets
      - ./config:/mnt/shared/config
      - ./data:/var/lib/kafka/data
      - ./log:/tmp/kraft-combined-logs
    environment:
      CLUSTER_ID: '5L6g3nShT-eMCtK--X86sw'
      KAFKA_ADVERTISED_LISTENERS: 'SSL://localhost:9092,SSL-INTERNAL://broker:19092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29092'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_INTER_BROKER_LISTENER_NAME: 'SSL-INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'SSL:SSL,CONTROLLER:PLAINTEXT,SSL-INTERNAL:SSL'
      KAFKA_LISTENERS: 'SSL://:9092,CONTROLLER://:29092,SSL-INTERNAL://:19092'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_NODE_ID: 1
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_SSL_KEY_CREDENTIALS: 'credentials'
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 'credentials'
      KAFKA_SSL_KEYSTORE_FILENAME: 'kafka.keystore.jks'
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 'credentials'
      KAFKA_SSL_TRUSTSTORE_FILENAME: 'kafka.truststore.jks'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
